// Element data: stats derived from real chemistry
// Light elements = fast/fragile, heavy = slow/tanky
const ELEMENTS = {
    H: {
        symbol: 'H',
        name: 'Hydrogen',
        atomicNum: 1,
        color: '#e8e8ff',
        mass: 1,
        speed: 8,
        health: 40,
        damage: 5,
        radius: 14,
        special: 'explosive',
        desc: 'Lightest & explosive',
    },
    He: {
        symbol: 'He',
        name: 'Helium',
        atomicNum: 2,
        color: '#fff4c8',
        mass: 2,
        speed: 7,
        health: 30,
        damage: 3,
        radius: 15,
        special: 'float',
        desc: 'Floats upward',
    },
    Be: {
        symbol: 'Be',
        name: 'Beryllium',
        atomicNum: 4,
        color: '#b8e0d0',
        mass: 4,
        speed: 7,
        health: 52,
        damage: 7,
        radius: 15,
        special: 'armor',
        desc: 'Lightweight & strong',
    },
    B: {
        symbol: 'B',
        name: 'Boron',
        atomicNum: 5,
        color: '#dd8844',
        mass: 5,
        speed: 7,
        health: 48,
        damage: 9,
        radius: 15,
        special: 'burn',
        desc: 'Metalloid that burns hot',
    },
    Li: {
        symbol: 'Li',
        name: 'Lithium',
        atomicNum: 3,
        color: '#cc80ff',
        mass: 3,
        speed: 7,
        health: 50,
        damage: 8,
        radius: 16,
        special: 'reactive',
        desc: 'Highly reactive',
    },
    C: {
        symbol: 'C',
        name: 'Carbon',
        atomicNum: 6,
        color: '#555555',
        mass: 6,
        speed: 5,
        health: 80,
        damage: 10,
        radius: 18,
        special: 'none',
        desc: 'Balanced & sturdy',
    },
    N: {
        symbol: 'N',
        name: 'Nitrogen',
        atomicNum: 7,
        color: '#4488ff',
        mass: 7,
        speed: 6,
        health: 60,
        damage: 8,
        radius: 17,
        special: 'freeze',
        desc: 'Freezing gas',
    },
    O: {
        symbol: 'O',
        name: 'Oxygen',
        atomicNum: 8,
        color: '#ff4444',
        mass: 8,
        speed: 6,
        health: 65,
        damage: 12,
        radius: 17,
        special: 'oxidize',
        desc: 'Combustion aura',
    },
    F: {
        symbol: 'F',
        name: 'Fluorine',
        atomicNum: 9,
        color: '#aaff44',
        mass: 9,
        speed: 7,
        health: 45,
        damage: 18,
        radius: 16,
        special: 'corrosive',
        desc: 'Corrosive aura',
    },
    Ne: {
        symbol: 'Ne',
        name: 'Neon',
        atomicNum: 10,
        color: '#ff6622',
        mass: 10,
        speed: 6,
        health: 35,
        damage: 4,
        radius: 17,
        special: 'glow',
        desc: 'Glows bright',
    },
    Na: {
        symbol: 'Na',
        name: 'Sodium',
        atomicNum: 11,
        color: '#8844cc',
        mass: 11,
        speed: 5,
        health: 55,
        damage: 14,
        radius: 20,
        special: 'reactive',
        desc: 'Explodes in water',
    },
    Mg: {
        symbol: 'Mg',
        name: 'Magnesium',
        atomicNum: 12,
        color: '#e8e8e8',
        mass: 12,
        speed: 5,
        health: 70,
        damage: 11,
        radius: 18,
        special: 'burn',
        desc: 'Burns brilliant white',
    },
    Al: {
        symbol: 'Al',
        name: 'Aluminum',
        atomicNum: 13,
        color: '#c0c0c0',
        mass: 13,
        speed: 5,
        health: 75,
        damage: 10,
        radius: 19,
        special: 'reflect',
        desc: 'Reflects projectiles',
    },
    Si: {
        symbol: 'Si',
        name: 'Silicon',
        atomicNum: 14,
        color: '#6688aa',
        mass: 14,
        speed: 4,
        health: 85,
        damage: 8,
        radius: 20,
        special: 'shield',
        desc: 'Damage-reducing shield',
    },
    P: {
        symbol: 'P',
        name: 'Phosphorus',
        atomicNum: 15,
        color: '#ff8800',
        mass: 15,
        speed: 5,
        health: 55,
        damage: 15,
        radius: 18,
        special: 'burn',
        desc: 'Burning aura',
    },
    S: {
        symbol: 'S',
        name: 'Sulfur',
        atomicNum: 16,
        color: '#ffee44',
        mass: 16,
        speed: 5,
        health: 55,
        damage: 14,
        radius: 18,
        special: 'toxic',
        desc: 'Choking SO₂ fumes',
    },
    Cl: {
        symbol: 'Cl',
        name: 'Chlorine',
        atomicNum: 17,
        color: '#88ff00',
        mass: 17,
        speed: 5,
        health: 50,
        damage: 16,
        radius: 18,
        special: 'toxic',
        desc: 'Toxic gas cloud',
    },
    Ar: {
        symbol: 'Ar',
        name: 'Argon',
        atomicNum: 18,
        color: '#a040ff',
        mass: 18,
        speed: 6,
        health: 40,
        damage: 5,
        radius: 18,
        special: 'glow',
        desc: 'Inert noble gas',
    },
    K: {
        symbol: 'K',
        name: 'Potassium',
        atomicNum: 19,
        color: '#dd66ff',
        mass: 19,
        speed: 4,
        health: 65,
        damage: 12,
        radius: 22,
        special: 'reactive',
        desc: 'Violently reactive',
    },
    Ca: {
        symbol: 'Ca',
        name: 'Calcium',
        atomicNum: 20,
        color: '#eeddcc',
        mass: 20,
        speed: 4,
        health: 90,
        damage: 8,
        radius: 21,
        special: 'armor',
        desc: 'Strong bones',
    },
    Sc: {
        symbol: 'Sc',
        name: 'Scandium',
        atomicNum: 21,
        color: '#a0c8e0',
        mass: 21,
        speed: 4,
        health: 85,
        damage: 11,
        radius: 19,
        special: 'shield',
        desc: 'Rare lightweight metal',
    },
    Ti: {
        symbol: 'Ti',
        name: 'Titanium',
        atomicNum: 22,
        color: '#708090',
        mass: 22,
        speed: 4,
        health: 95,
        damage: 12,
        radius: 20,
        special: 'armor',
        desc: 'Extremely strong & corrosion resistant',
    },
    V: {
        symbol: 'V',
        name: 'Vanadium',
        atomicNum: 23,
        color: '#6a5acd',
        mass: 23,
        speed: 4,
        health: 80,
        damage: 13,
        radius: 19,
        special: 'toxic',
        desc: 'Vanadium compounds are toxic',
    },
    Cr: {
        symbol: 'Cr',
        name: 'Chromium',
        atomicNum: 24,
        color: '#c0c8d0',
        mass: 24,
        speed: 3,
        health: 100,
        damage: 12,
        radius: 20,
        special: 'reflect',
        desc: 'Shiny chrome plating',
    },
    Mn: {
        symbol: 'Mn',
        name: 'Manganese',
        atomicNum: 25,
        color: '#5d4e37',
        mass: 25,
        speed: 3,
        health: 90,
        damage: 14,
        radius: 21,
        special: 'magnetic',
        desc: 'Ferromagnetic element',
    },
    Fe: {
        symbol: 'Fe',
        name: 'Iron',
        atomicNum: 26,
        color: '#aa6633',
        mass: 26,
        speed: 3,
        health: 120,
        damage: 15,
        radius: 22,
        special: 'magnetic',
        desc: 'Pulls enemies close',
    },
    Co: {
        symbol: 'Co',
        name: 'Cobalt',
        atomicNum: 27,
        color: '#3d5a80',
        mass: 27,
        speed: 3,
        health: 105,
        damage: 15,
        radius: 21,
        special: 'magnetic',
        desc: 'Permanent magnets',
    },
    Ni: {
        symbol: 'Ni',
        name: 'Nickel',
        atomicNum: 28,
        color: '#a0a0a8',
        mass: 28,
        speed: 3,
        health: 110,
        damage: 14,
        radius: 22,
        special: 'magnetic',
        desc: 'Ferromagnetic & tough',
    },
    Cu: {
        symbol: 'Cu',
        name: 'Copper',
        atomicNum: 29,
        color: '#cc7733',
        mass: 29,
        speed: 3,
        health: 100,
        damage: 14,
        radius: 22,
        special: 'electric',
        desc: 'Chain lightning',
    },
    Zn: {
        symbol: 'Zn',
        name: 'Zinc',
        atomicNum: 30,
        color: '#7088a0',
        mass: 30,
        speed: 3,
        health: 95,
        damage: 11,
        radius: 21,
        special: 'armor',
        desc: 'Galvanized plating',
    },
    As: {
        symbol: 'As',
        name: 'Arsenic',
        atomicNum: 33,
        color: '#556b2f',
        mass: 33,
        speed: 3,
        health: 70,
        damage: 16,
        radius: 19,
        special: 'toxic',
        desc: 'Infamous poison',
    },
    Br: {
        symbol: 'Br',
        name: 'Bromine',
        atomicNum: 35,
        color: '#cc2200',
        mass: 35,
        speed: 3,
        health: 70,
        damage: 18,
        radius: 20,
        special: 'toxic',
        desc: 'Corrosive liquid',
    },
    Rb: {
        symbol: 'Rb',
        name: 'Rubidium',
        atomicNum: 37,
        color: '#ff66aa',
        mass: 37,
        speed: 3,
        health: 60,
        damage: 14,
        radius: 20,
        special: 'reactive',
        desc: 'Violently reactive alkali',
    },
    Ru: {
        symbol: 'Ru',
        name: 'Ruthenium',
        atomicNum: 44,
        color: '#c0c0c8',
        mass: 44,
        speed: 3,
        health: 105,
        damage: 13,
        radius: 22,
        special: 'reflect',
        desc: 'Hard platinum-group metal',
    },
    Rh: {
        symbol: 'Rh',
        name: 'Rhodium',
        atomicNum: 45,
        color: '#e0e0e8',
        mass: 45,
        speed: 3,
        health: 110,
        damage: 13,
        radius: 22,
        special: 'reflect',
        desc: 'Mirror-grade reflectivity',
    },
    Pd: {
        symbol: 'Pd',
        name: 'Palladium',
        atomicNum: 46,
        color: '#b0b0c0',
        mass: 46,
        speed: 3,
        health: 105,
        damage: 13,
        radius: 22,
        special: 'electric',
        desc: 'Catalytic chain lightning',
    },
    Ag: {
        symbol: 'Ag',
        name: 'Silver',
        atomicNum: 47,
        color: '#d0d0e0',
        mass: 47,
        speed: 3,
        health: 110,
        damage: 12,
        radius: 23,
        special: 'reflect',
        desc: 'Reflects attacks',
    },
    Cd: {
        symbol: 'Cd',
        name: 'Cadmium',
        atomicNum: 48,
        color: '#dcb050',
        mass: 48,
        speed: 3,
        health: 100,
        damage: 15,
        radius: 23,
        special: 'toxic',
        desc: 'Toxic yellow pigment',
    },
    Sn: {
        symbol: 'Sn',
        name: 'Tin',
        atomicNum: 50,
        color: '#aab0b0',
        mass: 50,
        speed: 2,
        health: 95,
        damage: 10,
        radius: 24,
        special: 'armor',
        desc: 'Protective plating',
    },
    Xe: {
        symbol: 'Xe',
        name: 'Xenon',
        atomicNum: 54,
        color: '#4090ff',
        mass: 54,
        speed: 3,
        health: 70,
        damage: 8,
        radius: 22,
        special: 'glow',
        desc: 'Brilliant arc-lamp glow',
    },
    Au: {
        symbol: 'Au',
        name: 'Gold',
        atomicNum: 79,
        color: '#ffd700',
        mass: 79,
        speed: 2,
        health: 140,
        damage: 12,
        radius: 24,
        special: 'rich',
        desc: 'Bonus score on kill',
    },
    Hg: {
        symbol: 'Hg',
        name: 'Mercury',
        atomicNum: 80,
        color: '#99aacc',
        mass: 80,
        speed: 4,
        health: 80,
        damage: 20,
        radius: 22,
        special: 'toxic',
        desc: 'Toxic liquid metal',
    },
    Pb: {
        symbol: 'Pb',
        name: 'Lead',
        atomicNum: 82,
        color: '#445566',
        mass: 82,
        speed: 1,
        health: 160,
        damage: 18,
        radius: 26,
        special: 'heavy',
        desc: 'Heavy damage resistance',
    },
    U: {
        symbol: 'U',
        name: 'Uranium',
        atomicNum: 92,
        color: '#44ff88',
        mass: 92,
        speed: 1,
        health: 150,
        damage: 25,
        radius: 27,
        special: 'radioactive',
        desc: 'Damages nearby enemies',
    },
    Np: {
        symbol: 'Np',
        name: 'Neptunium',
        atomicNum: 93,
        color: '#44dd99',
        mass: 93,
        speed: 1,
        health: 145,
        damage: 26,
        radius: 26,
        special: 'radioactive',
        desc: 'Radioactive actinide',
    },
    Pu: {
        symbol: 'Pu',
        name: 'Plutonium',
        atomicNum: 94,
        color: '#88ffcc',
        mass: 94,
        speed: 1,
        health: 130,
        damage: 30,
        radius: 28,
        special: 'nuclear',
        desc: 'Massive death explosion',
    },
};

// Starter elements (available immediately)
const STARTER_ELEMENTS = ['H', 'He', 'C', 'O', 'Fe'];

// Elements unlocked per adventure level
const LEVEL_UNLOCKS = {
    1: ['Li', 'N', 'Na', 'Be', 'B'],
    2: ['Al', 'Si', 'Ca', 'Cu', 'Mg', 'S'],
    3: ['Ne', 'F', 'Cl', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Co', 'Ar', 'Ni', 'Zn'],
    4: ['U', 'Pu', 'Pb', 'Hg', 'Np'],
    5: ['P', 'K', 'Br', 'Ag', 'Sn', 'Au', 'As', 'Rb', 'Ru', 'Rh', 'Pd', 'Cd', 'Xe'],
};

const AURA_CONFIG = {
    radioactive: {
        cooldown: 1,
        radius: 80,
        damage: 3,
        effect: 'glow',
        color: '#44ff88',
        status: 'irradiated',
    },
    toxic: { cooldown: 2, radius: 60, damage: 5, effect: 'toxic', status: 'toxic' },
    freeze: { cooldown: 2, radius: 70, damage: 4, effect: 'freeze', status: 'frozen' },
    oxidize: { cooldown: 1.5, radius: 70, damage: 4, effect: 'sparks', status: 'burning' },
    corrosive: { cooldown: 1.5, radius: 60, damage: 6, effect: 'sparks', status: 'corroded' },
    burn: { cooldown: 1, radius: 55, damage: 5, effect: 'sparks', status: 'burning' },
};

// Per-frame status effects. Statuses are added via aura/projectile hits and
// resolved every tick in ElementEntity.applyStatusEffects.
//   dot:        HP lost per second while afflicted.
//   velocityMul: factor applied to (vx, vy) each frame, exp-scaled by dt.
//   takenMul:   multiplier on incoming damage while afflicted.
//   color:      tint for tick-damage popup.
const STATUS_EFFECTS = {
    burning: { dot: 4, color: '#ff8800' },
    toxic: { dot: 3, color: '#88ff00' },
    irradiated: { dot: 2, color: '#44ff88' },
    corroded: { dot: 2, takenMul: 1.15, color: '#aaff44' },
    frozen: { velocityMul: 0.4, color: '#88ccff' },
    shocked: { takenMul: 1.2, color: '#44ddff' },
};

const SPECIALS = {
    none: {},
    explosive: {
        death: { radius: 100, damage: 30 },
    },
    reactive: {
        death: { radius: 100, damage: 30 },
    },
    nuclear: {
        death: { radius: 200, damage: 50, nuclear: true },
    },
    float: {
        frictionAir: 0.09,
        passiveForce: { x: 0, y: -0.0004 },
    },
    heavy: {
        frictionAir: 0.01,
        damageTakenMultiplier: 0.8,
    },
    armor: {
        damageTakenMultiplier: 0.7,
    },
    shield: {
        damageTakenMultiplier: 0.75,
    },
    reflect: {
        reflectChance: 0.3,
    },
    glow: {
        visual: 'glow',
    },
    rich: {
        scoreBonus: 100,
    },
    magnetic: {
        magnetic: { radius: 120, force: 0.0005 },
    },
    electric: {
        chain: { cooldown: 2, range: 150, damage: 10, maxTargets: 3 },
    },
    radioactive: { aura: AURA_CONFIG.radioactive },
    toxic: { aura: AURA_CONFIG.toxic },
    freeze: { aura: AURA_CONFIG.freeze },
    oxidize: { aura: AURA_CONFIG.oxidize },
    corrosive: { aura: AURA_CONFIG.corrosive },
    burn: { aura: AURA_CONFIG.burn },
};

// Damage multipliers keyed by attacker.special → defender.special.
// Attacker keys are usually "type" archetypes (burn, freeze, corrosive,
// radioactive, electric, toxic, oxidize); defender keys can be either
// a defensive trait (armor, shield, heavy, reflect) or another type
// the attacker has an interaction with (burn vs freeze, etc.).
// Multipliers are kept gentle (1.10–1.25) — the goal is flavorful
// matchups, not rock-paper-scissors steamrolling.
const ELEMENT_EFFECTIVENESS = {
    corrosive: { armor: 1.2, shield: 1.15, heavy: 1.1, reflect: 1.1 },
    burn: { freeze: 1.15, reactive: 1.25, float: 1.2, toxic: 1.1 },
    freeze: { burn: 1.15, float: 1.1, oxidize: 1.15 },
    radioactive: { heavy: 1.1, armor: 1.1, shield: 1.1 },
    electric: { shield: 1.15, magnetic: 1.2, armor: 1.1, reflect: 1.1 },
    toxic: { armor: 1.1, shield: 1.1, heavy: 1.05 },
    oxidize: { reactive: 1.2, heavy: 1.1, freeze: 1.1 },
};

function getSpecialConfig(specialKey) {
    return SPECIALS[specialKey] || SPECIALS.none;
}

// Accepts an entity ({ data: { special } }), a normalized { special }, or a raw
// special-key string for either side, resolving each to its special key.
function getEffectivenessMultiplier(attacker, defender) {
    const attackerKey = attacker?.data?.special || attacker?.special || attacker || 'none';
    const defenderKey = defender?.data?.special || defender?.special || defender || 'none';
    return ELEMENT_EFFECTIVENESS[attackerKey]?.[defenderKey] || 1;
}

function resolveElementDamage(
    defender,
    amount,
    effects,
    attacker = null,
    entities = null,
    options = {},
) {
    if (!defender || !defender.alive || defender.invulnTimer > 0) return 0;

    const attackerSpecial = options.attackerSpecial || attacker?.data?.special || 'none';
    const special = getSpecialConfig(defender.data.special);
    let resolved = amount * getEffectivenessMultiplier({ special: attackerSpecial }, defender);

    if (typeof special.damageTakenMultiplier === 'number') {
        resolved *= special.damageTakenMultiplier;
    }

    // Per-status take-damage multipliers (shocked, corroded, …)
    for (const [key] of defender.statuses) {
        const cfg = STATUS_EFFECTS[key];
        if (cfg?.takenMul) resolved *= cfg.takenMul;
    }

    if (options.status) {
        defender.addStatus(options.status, options.statusDuration || 1.5, attacker);
    }

    defender.health -= resolved;
    defender.flashTimer = 0.15;

    if (effects) {
        effects.damageNumber(defender.body.position.x, defender.body.position.y, resolved);
        effects.sparks(defender.body.position.x, defender.body.position.y, defender.data.color);
    }

    playSound('hit');

    if (defender.health <= 0) {
        defender.die(entities || defender.entitiesContext, effects);
    }

    return resolved;
}

// All element keys in order
const ALL_ELEMENT_KEYS = Object.keys(ELEMENTS);

// Get sorted elements by atomic number
function getElementsSorted() {
    return [...ALL_ELEMENT_KEYS].sort((a, b) => ELEMENTS[a].atomicNum - ELEMENTS[b].atomicNum);
}
